### PR TITLE
Basic changes for PowerPC

### PR DESCRIPTION
**Pull request by michelmno**
do not try to report flags for PowerPC

Signed-off-by: Michel Normand <normand@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by workhorsy** [comment]
I'm working on rebuilding my Debian Qemu PPC system right now. I want to be able to test this before merging.

**Comment by gut** [comment]
Hi. I was curious about how is this project working on POWER8 and I wanted to show the outputs of my machine running on bare-metal:
https://gist.github.com/gut/6a7531a3af4b3086664781b18f1cc6f0

I hope it helps in order to review this PR. (still, it needs to be updated)

**Comment by workhorsy** [comment]
I'm still working on trying to add full PPC support. It is very difficult, because I don't have access to any PPC machines. I've had a small amount of success getting Debian 8 PPC64le running in Qemu. But I'm still not sure how to get PPC CPU flags.

Unfortunately this pull request looks quite outdated. Most of what it does, has been duplicated while I was trying to add PPC features. Is there anything in this PR that needs to be merged still?

What other PPC information would you like to show in py-cpuinfo?

**Comment by leitao** [comment]
hi @workhorsy, you can request a VM at our public servers. It is free and you can use for development.
Please go to http://openpower.ic.unicamp.br/minicloud/ to request.

**Comment by workhorsy** [comment]
Thanks @leitao . I made a request for a MiniCloud VM. Hopefully it works out for us.

**Comment by leitao** [comment]
Sure. If it does not work, let me know and I can help to influence.

**Comment by gut** [comment]
@workhorsy : Hi, how did it go? Did you encounter any issues when registering on MiniCloud?

**Comment by workhorsy** [comment]
I got registered for MiniCloud. I still have to read the docs to figure out how to set things up. I've been super busy at work for the past few days. Hopefully I will have time to do it soon.

**Comment by workhorsy** [comment]
I got PPC CPU flags working in the new 3.1.0 release. So I'll close this PR for now. Thanks for your help everyone.

**Comment by gut** [comment]
@workhorsy Hi, thanks for your 3.1.0 release update!
I tried it on my Ubuntu 17.10 POWER8 virtual machine and it looks broken at the moment:
```
$ python ./cpuinfo/cpuinfo.py
Traceback (most recent call last):
  File "./cpuinfo/cpuinfo.py", line 1830, in <module>
    main()
  File "./cpuinfo/cpuinfo.py", line 1797, in main
    info = get_cpu_info()
  File "./cpuinfo/cpuinfo.py", line 1774, in get_cpu_info
    CopyNewFields(info, _get_cpu_info_from_ibm_pa_features())
  File "./cpuinfo/cpuinfo.py", line 1335, in _get_cpu_info_from_ibm_pa_features
    left, right = value.split(' ')
ValueError: too many values to unpack
```

And this is the reason:
```
$ lsprop /proc/device-tree/cpus/*/ibm,pa-features
/proc/device-tree/cpus/PowerPC,POWER8@0/ibm,pa-features
                 18 00 f6 3f c7 c0 80 f0 80 00 00 00 00 00 00 00...?............
                 00 00 80 00 80 00 80 00 80 00                  ..........
/proc/device-tree/cpus/PowerPC,POWER8@8/ibm,pa-features
                 18 00 f6 3f c7 c0 80 f0 80 00 00 00 00 00 00 00...?............
                 00 00 80 00 80 00 80 00 80 00                  ..........
```

Whereas when running on the host it's:
```
$ lsprop /proc/device-tree/cpus/*/ibm,pa-features
/proc/device-tree/cpus/PowerPC,POWER8@20/ibm,pa-features
                 0600f63f c70080c0
/proc/device-tree/cpus/PowerPC,POWER8@28/ibm,pa-features
                 0600f63f c70080c0
/proc/device-tree/cpus/PowerPC,POWER8@30/ibm,pa-features
                 0600f63f c70080c0
/proc/device-tree/cpus/PowerPC,POWER8@60/ibm,pa-features
                 0600f63f c70080c0
/proc/device-tree/cpus/PowerPC,POWER8@70/ibm,pa-features
                 0600f63f c70080c0
/proc/device-tree/cpus/PowerPC,POWER8@a0/ibm,pa-features
                 0600f63f c70080c0
/proc/device-tree/cpus/PowerPC,POWER8@a8/ibm,pa-features
                 0600f63f c70080c0
/proc/device-tree/cpus/PowerPC,POWER8@e0/ibm,pa-features
                 0600f63f c70080c0
/proc/device-tree/cpus/PowerPC,POWER8@e8/ibm,pa-features
                 0600f63f c70080c0
/proc/device-tree/cpus/PowerPC,POWER8@f0/ibm,pa-features
                 0600f63f c70080c0
```

*ps: it worked as expected on the host (also an Ubuntu 17.10):*
```
$ python ./cpuinfo/cpuinfo.py
cpuinfo version: (3, 1, 0)
Vendor ID:
Hardware Raw:
Brand: POWER8E (raw), altivec supported
Hz Advertised: 3.6900 GHz
Hz Actual: 3.6900 GHz
Hz Advertised Raw: (3690000000, 0)
Hz Actual Raw: (3690000000, 0)
Arch: PPC_64
Bits: 64
Count: 80
Raw Arch String: ppc64le
L2 Cache Size:
L2 Cache Line Size:
L2 Cache Associativity:
Stepping:
Model:
Family:
Processor Type:
Extended Model:
Extended Family:
Flags: dabr, dabrx, dsisr, fpu, lp, mmu, pp, rislb, run, slb, sprg3, ugr_in_dscr
```

I hope it helps.

**Comment by workhorsy** [comment]
Interesting @gut. Looks like ibm,pa-features is formatted different for some reason. What virtual machine software are you using?

Also, I'm turning you bug into a new bug here: #68

**Pull request closed without merging**
